version: '3'
services:
  development:
    build: .
    expose:
      - "1234"
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    command: sh -c "cp countries.geojson dist && npm run start"
